<?php
/**
 * Copyright © Tlawanah, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var Tlawanah\Customer\Block\Account\Customer $block */
?>
<?php if($block->customerLoggedIn()): ?>    
    <?php if($block->getChildHtml()):?>
    <div class="customer-menu" data-target="dropdown">
        <?= $block->getChildHtml() ?>
    </div>
    <?php endif; ?>    
<?php endif; ?>
